"""Generation service - handles report generation workflow."""

import subprocess
import json
import sys
from pathlib import Path
from typing import Optional
import asyncio
import os

from app.config import BASE_DIR


def generate_metrics(ticker: str, background: bool = False) -> bool:
    """
    Execute the metrics generation script for a ticker.
    
    Args:
        ticker: Stock ticker symbol (e.g., AAPL, REP.MC)
    
    Returns:
        True if metrics generation was successful, False otherwise
    """
    try:
        # Path to the metrics generation script
        script_path = (
            BASE_DIR / ".github" / "skills" / "yfinance-report" / 
            "scripts" / "generate_metrics_from_yfinance.py"
        )
        
        if not script_path.exists():
            print(f"Warning: Metrics generation script not found at {script_path}")
            return False
        
        # Execute the script with the ticker
        if background:
            # Start in background and don't wait
            try:
                subprocess.Popen([sys.executable, str(script_path), ticker],
                                 stdout=subprocess.DEVNULL,
                                 stderr=subprocess.DEVNULL)
                print(f"Metrics generation started in background for {ticker}")
                return True
            except Exception as e:
                print(f"Failed to start background metrics generation for {ticker}: {e}")
                return False
        else:
            result = subprocess.run(
                [sys.executable, str(script_path), ticker],
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if result.returncode == 0:
                print(f"Metrics generated successfully for {ticker}")
                if result.stdout:
                    print(result.stdout)
                return True
            else:
                print(f"Error generating metrics for {ticker}")
                if result.stderr:
                    print(f"Error details: {result.stderr}")
                return False
            
    except subprocess.TimeoutExpired:
        print(f"Metrics generation timeout for {ticker}")
        return False
    except Exception as e:
        print(f"Exception during metrics generation for {ticker}: {e}")
        return False


async def trigger_generation(ticker: str) -> dict:
    """
    Trigger the financial report generation workflow.
    
    If reports already exist, automatically generates metrics data.
    """
    
    # Validate ticker format
    if not ticker or not all(c.isalnum() or c == '.' for c in ticker):
        return {
            "status": "error",
            "message": f"Invalid ticker format: {ticker}"
        }
    
    ticker = ticker.upper()
    
    # Check if reports already exist (assuming they were generated by the agent)
    report_dir = Path("evaluaciones") / ticker
    final_report = report_dir / "informe-final.md"
    metrics_file = report_dir / "raw-search" / "metrics.json"
    
    if final_report.exists():
        # Reports exist, so generate metrics automatically
        print(f"Reports found for {ticker}, generating metrics...")
        # Start metrics generation in background to avoid blocking
        generate_metrics(ticker, background=True)

        return {
            "status": "started",
            "ticker": ticker,
            "phases": ["tecnico", "fundamentales", "berkshire", "final"],
            "current_phase": "metrics",
            "progress_percent": 90,
            "message": "Reports detected. Metrics generation started in background."
        }

    # Reports don't exist yet - indicate that generation workflow is started/ready
    return {
        "status": "started",
        "ticker": ticker,
        "phases": ["tecnico", "fundamentales", "berkshire", "final"],
        "current_phase": "tecnico",
        "progress_percent": 0,
        "message": "Report generation workflow initiated. Use @analista-financiero agent to generate reports."
    }


async def get_generation_progress(ticker: str) -> dict:
    """Get current generation progress."""
    
    report_dir = Path("evaluaciones") / ticker
    metrics_file = report_dir / "raw-search" / "metrics.json"
    
    if metrics_file.exists():
        return {
            "status": "completed",
            "ticker": ticker,
            "phases": ["tecnico", "fundamentales", "berkshire", "final"],
            "current_phase": "metrics",
            "progress_percent": 100,
            "message": "All reports and metrics generated"
        }

    final_report = report_dir / "informe-final.md"
    if final_report.exists():
        return {
            "status": "in_progress",
            "ticker": ticker,
            "phases": ["tecnico", "fundamentales", "berkshire", "final"],
            "current_phase": "metrics",
            "progress_percent": 90,
            "message": "Generating metrics data..."
        }

    return {
        "status": "in_progress",
        "ticker": ticker,
        "phases": ["tecnico", "fundamentales", "berkshire", "final"],
        "current_phase": "reports",
        "progress_percent": 50,
        "message": "Generating financial reports..."
    }


async def check_generation_complete(ticker: str) -> Optional[dict]:
    """Check if generation is complete."""
    
    report_path = Path("evaluaciones") / ticker / "informe-final.md"
    metrics_path = Path("evaluaciones") / ticker / "raw-search" / "metrics.json"
    
    if report_path.exists() and metrics_path.exists():
        return {
            "status": "completed",
            "ticker": ticker,
            "url": f"/report/{ticker}",
            "message": "All reports and metrics ready"
        }
    elif report_path.exists():
        return {
            "status": "partial",
            "ticker": ticker,
            "url": f"/report/{ticker}",
            "message": "Reports ready, generating metrics..."
        }
    
    return None
